// <auto-generated />
using System;
using HRCase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRCase.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRCase.Models.Approval", b =>
                {
                    b.Property<int>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalId"));

                    b.Property<DateTime>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApprovalId");

                    b.HasIndex("CaseId");

                    b.ToTable("Approvals");
                });

            modelBuilder.Entity("HRCase.Models.DisciplinaryCase", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseId"));

                    b.Property<DateTime>("CaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Violation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CaseId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("DisciplinaryCases");
                });

            modelBuilder.Entity("HRCase.Models.ENTblData", b =>
                {
                    b.Property<int>("AutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("autoid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutoId"));

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("agent");

                    b.Property<string>("COCGeneralProvision")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("COC_General_Provision");

                    b.Property<string>("COCProgression")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("COC_Progression");

                    b.Property<string>("COCSpecificProvision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COC_Specific_Provision");

                    b.Property<string>("CodeId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("codeid");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("currentstatus");

                    b.Property<DateTime?>("DAFSignedTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DAF_Signed_Time");

                    b.Property<string>("DOJ")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DOJ");

                    b.Property<DateTime?>("DateCFCreatedByPR")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_CF_Created_by_PR");

                    b.Property<DateTime?>("DateCFReceivedByEmployee")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_CF_Received_by_Employee");

                    b.Property<DateTime?>("DateCFSentToHR")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_CF_Sent_to_HR");

                    b.Property<DateTime?>("DateCFSignedReturnedByHR")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_CF_Signed_Returned_by_HR");

                    b.Property<DateTime?>("DateDAFCreatedByPR")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_DAF_Created_by_PR");

                    b.Property<DateTime?>("DateDAFReceivedByEmployee")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_DAF_Received_by_Employee");

                    b.Property<DateTime?>("DateDAFSignedReturnedByHR")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_DAF_Signed_Returned_by_HR");

                    b.Property<DateTime?>("DateDAFSubmittedToHRByPR")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_DAF_Submitted_to_HR_by_PR");

                    b.Property<DateTime?>("DateEndorsedToLR")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_Endorsed_to_LR");

                    b.Property<DateTime?>("DateOfFollowup")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateoffollowup");

                    b.Property<string>("DateOfOffense")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Date_of_Offense");

                    b.Property<DateTime?>("DateReturnedByLRToHRBP")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_Returned_by_LR_to_HRBP");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Department");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Designation");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Details");

                    b.Property<string>("DisciplinaryAction")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Disciplinary_Action");

                    b.Property<string>("EmpId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("empid");

                    b.Property<string>("EmployeeReply")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Employee_Reply");

                    b.Property<DateTime?>("EmployeeReplyTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Employee_Reply_Time");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Employment_Status");

                    b.Property<string>("EmploymentStautus")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Employment_Stautus");

                    b.Property<DateTime?>("FinalizedTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Finalized_Time");

                    b.Property<string>("Findings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Findings");

                    b.Property<string>("HRBP")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("HRBP");

                    b.Property<string>("HRBPAVP")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("HRBP_AVP");

                    b.Property<string>("HRBPAVPApproval")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HRBP_AVP_Approval");

                    b.Property<string>("HRBPAVPId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HRBP_AVP_ID");

                    b.Property<string>("HRBPAVPRemarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HRBP_AVP_Remarks");

                    b.Property<string>("HRBPApproval")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HRBP_Approval");

                    b.Property<string>("HRBPId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HRBP_ID");

                    b.Property<string>("HRBPRemarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HRBP_Remarks");

                    b.Property<DateTime?>("HRBPTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("HRBP_Time");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("history");

                    b.Property<string>("LR")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("LR");

                    b.Property<string>("LRApproval")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LR_Approval");

                    b.Property<string>("LRId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LR_ID");

                    b.Property<string>("LRRemarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LR_Remarks");

                    b.Property<DateTime?>("LRTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("LR_Time");

                    b.Property<string>("PlatformLOB")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Platform_LOB");

                    b.Property<string>("PrimaryReportee")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Primary_Reportee");

                    b.Property<string>("PrimaryReporteeApproval")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Primary_Reportee_Approval");

                    b.Property<string>("PrimaryReporteeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Primary_Reportee_ID");

                    b.Property<string>("PrimaryReporteeRemarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Primary_Reportee_Remarks");

                    b.Property<DateTime?>("PrimaryReporteeTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Primary_Reportee_Time");

                    b.Property<string>("ResolutionHRBP")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Resolution_HRBP");

                    b.Property<string>("ResolutionHRBPApproval")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Resolution_HRBP_Approval");

                    b.Property<string>("ResolutionHRBPId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Resolution_HRBP_ID");

                    b.Property<string>("ResolutionHRBPRemarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Resolution_HRBP_Remarks");

                    b.Property<DateTime?>("ResolutionHRBPTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Resolution_HRBP_Time");

                    b.Property<string>("ResolutionSR")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Resolution_SR");

                    b.Property<string>("ResolutionSRApproval")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Resolution_SR_Approval");

                    b.Property<string>("ResolutionSRId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Resolution_SR_ID");

                    b.Property<string>("ResolutionSRRemarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Resolution_SR_Remarks");

                    b.Property<DateTime?>("ResolutionSRTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Resolution_SR_Time");

                    b.Property<DateTime?>("ResolutionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Resolution_Time");

                    b.Property<string>("SecondaryReportee")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Secondary_Reportee");

                    b.Property<string>("SecondaryReporteeApproval")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Secondary_Reportee_Approval");

                    b.Property<string>("SecondaryReporteeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Secondary_Reportee_ID");

                    b.Property<string>("SecondaryReporteeRemarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Secondary_Reportee_Remarks");

                    b.Property<DateTime?>("SecondaryReporteeTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Secondary_Reportee_Time");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("sender");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sender_ID");

                    b.Property<DateTime?>("SeparationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("SEPARATION_DATE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("statusdate");

                    b.HasKey("AutoId");

                    b.HasIndex("EmpId");

                    b.ToTable("ENTblData");
                });

            modelBuilder.Entity("HRCase.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HRCase.Models.TblEmpLog", b =>
                {
                    b.Property<int>("AutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("autoid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutoId"));

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("accesslevel");

                    b.Property<string>("AccountHandled")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("accounthandled");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("address");

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("agent");

                    b.Property<string>("Bldg")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("bldg");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTime?>("CertificationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("certificationdate");

                    b.Property<string>("CodeId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("codeid");

                    b.Property<string>("ContactNum")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("contactnum");

                    b.Property<DateTime?>("DateOfEntry")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateofentry");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("email");

                    b.Property<string>("EmpId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("empid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("firstname");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gender");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("grade");

                    b.Property<string>("HealthCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HealthCard");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("hiredate");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("imageurl");

                    b.Property<DateTime?>("LastBulkUpdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastbulkupdate");

                    b.Property<DateTime?>("LastEntry")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastentry");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("LineHr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("linehr");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("location");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("middlename");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nickname");

                    b.Property<string>("NtLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ntlogin");

                    b.Property<string>("Pagibig")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("pagibig");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("Philhealth")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("philhealth");

                    b.Property<string>("PrimaryEmpId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("primaryempid");

                    b.Property<string>("PrimaryReport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("primaryreport");

                    b.Property<DateTime?>("RegularizationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("regularizationdate");

                    b.Property<string>("ResetBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ResetBy");

                    b.Property<DateTime?>("ResetDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ResetDate");

                    b.Property<string>("SecondaryEmpId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("secondaryempid");

                    b.Property<string>("SecondaryReport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("secondaryreport");

                    b.Property<DateTime?>("SeparationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("separationdate");

                    b.Property<string>("Sss")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sss");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Tin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tin");

                    b.Property<string>("Title1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title1");

                    b.Property<string>("Title2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title2");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("unit");

                    b.Property<short?>("UpdateFlag")
                        .HasColumnType("smallint")
                        .HasColumnName("UpdateFlag");

                    b.Property<string>("Uploader")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("uploader");

                    b.Property<string>("VerifyInfo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("verifyinfo");

                    b.HasKey("AutoId");

                    b.ToTable("TblEmpLog");
                });

            modelBuilder.Entity("HRCase.Models.Approval", b =>
                {
                    b.HasOne("HRCase.Models.DisciplinaryCase", "DisciplinaryCase")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DisciplinaryCase");
                });

            modelBuilder.Entity("HRCase.Models.DisciplinaryCase", b =>
                {
                    b.HasOne("HRCase.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRCase.Models.ENTblData", b =>
                {
                    b.HasOne("HRCase.Models.TblEmpLog", "Employee")
                        .WithMany("DisciplinaryCases")
                        .HasForeignKey("EmpId")
                        .HasPrincipalKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRCase.Models.TblEmpLog", b =>
                {
                    b.Navigation("DisciplinaryCases");
                });
#pragma warning restore 612, 618
        }
    }
}
